[package]
name = "jwtrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = { version = "8.3.0" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }
axum = { version = "0.6", features = ["headers", "macros"] }
serde_json = "1.0.104"
async-trait = "0.1.72"
hyper = { version = "0.14.27", features = ["full"] }
tower = "0.4.13"


[[example]]
name = "axum"
